# Servidor
server.port=8080

# H2 Database (persistido em arquivo)
spring.datasource.url=jdbc:h2:file:./data/mvctransportes
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# JPA
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Nome da aplicação
spring.application.name=mvc-transportes-core

# Desliga warning do open-in-view
spring.jpa.open-in-view=false